version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo

  restore_env: &restore_env
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/ci.txt" }}
        - v1-dependencies

jobs:
  test:
    <<: *container_config

    steps:
      - checkout
      - *restore_env
      - run:
          name: install packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .[ci]
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/ci.txt" }}
      - run:
          name: check Readme syntax
          command: |
            . venv/bin/activate
            python setup.py sdist
            twine check dist/*

  verify_tag:
    <<: *container_config
    steps:
      - checkout
      - *restore_env
      - run:
          name: verify git tag vs. version
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py verify

  release:
    <<: *container_config
    steps:
      - checkout
      - *restore_env
      - add_ssh_keys
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            # create a source distribution
            python setup.py sdist

            # create a wheel
            python setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - verify_tag
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master